name: portfolio
description: Adithya Vardhan Reddy - Flutter Developer Portfolio
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  flutter_animate: ^4.5.0
  http: ^1.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
